# Site settings
title: The Journal of Byrnian Mechanics
email: jbyrnianmechanics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Journal of Byrnian Mechanics is a repository for answers to the deep questions that plague all scientists in their moments of intrigue (or at least two bored Ph.D. students who should be demonstrating). Any opinions posted are those of the author(s) alone, and do not represent any institution.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mm14kwn.github.io/jbm" # the base hostname & protocol for your site
twitter_username: KNewmanOcean
github_username:  mm14kwn

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Home
    link: https://mm14kwn.github.io/jbm/
  option2:
    name: About
    link: https://mm14kwn.github.io/jbm/about/
  option3:
    name: Our Inspiration
    link: http://what-if.xkcd.com

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown